# Generated by Django 3.2.15 on 2022-10-24 16:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=9, unique=True)),
                ('phrase', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('day_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='planer.week', unique=True)),
            ],
            options={
                'ordering': ['day_number', 'created_on'],
            },
        ),
    ]
