# Generated by Django 3.2.15 on 2022-10-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0002_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='planer.week'),
        ),
    ]
