# Generated by Django 3.2.15 on 2022-10-24 16:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0003_alter_day_day_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.DecimalField(decimal_places=0, max_digits=1, unique=True)),
                ('meal_name', models.CharField(max_length=30)),
                ('meal_description', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='planer.day')),
            ],
            options={
                'ordering': ['meal_number', 'created_on'],
            },
        ),
    ]
