# Generated by Django 3.2.15 on 2022-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0004_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'Published')], default=0),
        ),
    ]
