# Generated by Django 3.2.15 on 2022-10-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0007_alter_day_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='planer.week'),
        ),
    ]
