# Generated by Django 3.2.15 on 2022-11-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer', '0008_alter_day_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='day', to=settings.AUTH_USER_MODEL),
        ),
    ]
