# Generated by Django 3.2.15 on 2022-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0009_day_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='slug',
            field=models.SlugField(default=models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], default=0), max_length=200, unique=True),
        ),
    ]
