# Generated by Django 3.2.15 on 2022-11-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0010_day_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.AlterField(
            model_name='day',
            name='day_name',
            field=models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='planer.week'),
        ),
    ]
