# Generated by Django 3.2.15 on 2022-11-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0012_auto_20221115_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
