# Generated by Django 3.2.15 on 2022-11-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0013_meal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['week_owner', 'created_on']},
        ),
        migrations.RenameField(
            model_name='day',
            old_name='day_number',
            new_name='week_owner',
        ),
    ]
