# Generated by Django 3.2.15 on 2022-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0014_auto_20221115_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='slug',
            new_name='slugmeal',
        ),
        migrations.AddField(
            model_name='day',
            name='slugday',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
