# Generated by Django 3.2.15 on 2022-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0015_auto_20221116_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_title',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
