# Generated by Django 3.2.15 on 2022-11-22 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer', '0017_alter_day_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['owner', 'slugmeal', 'created_on']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_number',
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='slugmeal',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
