# Generated by Django 3.2.15 on 2022-11-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0018_auto_20221122_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['owner', 'meal_day', 'slugmeal', 'created_on']},
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planer.day'),
            preserve_default=False,
        ),
    ]
