# Generated by Django 3.2.15 on 2022-11-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer', '0019_auto_20221122_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='planer.day'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
