# Generated by Django 3.2.15 on 2022-11-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0020_auto_20221122_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['owner', 'slugmeal', 'created_on']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_day',
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planer.day'),
            preserve_default=False,
        ),
    ]
