# Generated by Django 3.2.15 on 2022-11-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0022_meal_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slugmeal',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
