# Generated by Django 3.2.15 on 2022-11-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0023_alter_meal_slugmeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['owner', 'title', 'created_on']},
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='slugmeal',
            new_name='title',
        ),
    ]
