# Generated by Django 3.2.15 on 2022-11-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0025_remove_day_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_title',
            new_name='title',
        ),
    ]
