# Generated by Django 3.2.15 on 2022-11-23 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0033_auto_20221123_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planer.day'),
        ),
    ]
