# Generated by Django 3.2.15 on 2022-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0034_alter_meal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'Published')], default=0),
        ),
    ]
