# Generated by Django 3.2.15 on 2022-11-23 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer', '0035_day_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
    ]
