# Generated by Django 3.2.15 on 2022-11-23 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer', '0036_auto_20221123_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meal'],
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, default=' ', max_length=10)),
                ('description', models.DateField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='planer.mealplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('user', 'meal'), name='meal_id'),
        ),
    ]
