# Generated by Django 3.2.15 on 2022-11-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0037_auto_20221123_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='food',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
