# Generated by Django 3.2.15 on 2022-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0038_auto_20221123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
