# Generated by Django 3.2.15 on 2022-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.EmailField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
